spring:
  application.name: bookie
  thymeleaf.cache: false
  devtools.restart.enabled: true

  sql:
    init.mode: never # schema.sql 사용하지 않음

  datasource:
    url: jdbc:h2:file:./data/bookie;DB_CLOSE_ON_EXIT=TRUE;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.format_sql: true
      hibernate.globally_quoted_identifiers: true # 테이블 및 컬럼 이름을 자동으로 큰따옴표 처리

  show-sql: true

logging:
  level:
    org.springframework.core.env: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

