spring:
  application.name: bookie
  devtools.restart.enabled: true

  sql:
    init:
      mode: always
      schema-locations: classpath:sqls/maria-schema.sql
      #data-locations: classpath:sqls/maria-data.sql

  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/bookie_dev
    username: bookie_dev
    password: bookie_dev
    #hikari:
      #maximum-pool-size: 10
      #minimum-idle: 5
      #idle-timeout: 30000
      #max-lifetime: 1800000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect
      hibernate.format_sql: true



logging:
  level:
    #org.springframework.core.env: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG

