spring:
  sql:
    init:
      mode: always
      schema-locations: classpath:sqls/h2-schema.sql
      #data-locations: classpath:sqls/data.sql

  datasource:
    #url: jdbc:h2:file:./data/bookie;DB_CLOSE_ON_EXIT=TRUE;AUTO_SERVER=TRUE
    url: jdbc:h2:mem:bookie;DB_CLOSE_ON_EXIT=TRUE
    driverClassName: org.h2.Driver
    username: sa
    hibernate.dialect: org.hibernate.dialect.H2Dialect


