spring:
  application.name: bookie
  devtools.restart.enabled: true

  sql:
    init:
      mode: always
      schema-locations: classpath:sqls/h2-schema.sql
      #data-locations: classpath:sqls/data.sql

  datasource:
    #url: jdbc:h2:file:./data/bookie;DB_CLOSE_ON_EXIT=TRUE;AUTO_SERVER=TRUE
    url: jdbc:h2:mem:bookie;DB_CLOSE_ON_EXIT=TRUE
    driverClassName: org.h2.Driver
    username: sa

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.format_sql: true
      #hibernate.globally_quoted_identifiers: true



logging:
  level:
    org.springframework.core.env: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.sql: DEBUG
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG

