
-- 외래 키 제약 조건 삭제
ALTER TABLE `REVIEW` DROP FOREIGN KEY `FK_REVIEW_APPUSER`;
ALTER TABLE `REVIEW` DROP FOREIGN KEY `FK_REVIEW_BOOK`;

-- 테이블 삭제
DROP TABLE IF EXISTS `REVIEW`;
DROP TABLE IF EXISTS `BOOK`;
DROP TABLE IF EXISTS `APPUSER`;

CREATE TABLE `APPUSER` (
	`TSID`	VARCHAR(100)	NOT NULL,
	`ID`	VARCHAR(50)	NULL,
	`PASSWORD`	VARCHAR(255)	NULL,
	`NICKNAME`	VARCHAR(50)	NULL,
	`EMAIL`	VARCHAR(100)	NULL,
	`ROLE`	VARCHAR(20)	NULL,
	`CREATED_ON`	TIMESTAMP	NULL,
	`MODIFIED_ON`	TIMESTAMP	NULL
);

CREATE TABLE `BOOK` (
	`TSID`	VARCHAR(50)	NOT NULL,
	`TITLE`	VARCHAR(255)	NULL,
	`AUTHOR`	VARCHAR(50)	NULL,
	`PUBLISHED_DATE`	VARCHAR(50)	NULL,
	`ISBN`	VARCHAR(50)	NULL,
	`DESCRIPTION` LONGTEXT NULL,
	`THUMBNAIL_URL`	VARCHAR(500)	NULL,
	`CREATED_ON`	TIMESTAMP	NULL,
	`MODIFIED_ON`	TIMESTAMP	NULL
);

CREATE TABLE `REVIEW` (
	`TSID`	VARCHAR(100)	NOT NULL,
	`APPUSER_TSID`	VARCHAR(100)	NOT NULL,
	`BOOK_TSID`	VARCHAR(100)	NOT NULL,
	`CONTENT`	LONGTEXT	NULL,
	`RATE`	DECIMAL(2,1)	NULL,
	`CREATED_ON`	TIMESTAMP	NULL,
	`MODIFIED_ON`	TIMESTAMP	NULL
);

ALTER TABLE `APPUSER` ADD CONSTRAINT `PK_APPUSER` PRIMARY KEY (
	`TSID`
);

ALTER TABLE `BOOK` ADD CONSTRAINT `PK_BOOK` PRIMARY KEY (
	`TSID`
);

ALTER TABLE `REVIEW` ADD CONSTRAINT `PK_REVIEW` PRIMARY KEY (
	`TSID`
);

-- 외래 키 추가: REVIEW.APPUSER_TSID -> APPUSER.TSID
ALTER TABLE `REVIEW`
ADD CONSTRAINT `FK_REVIEW_APPUSER`
FOREIGN KEY (`APPUSER_TSID`) REFERENCES `APPUSER` (`TSID`);

-- 외래 키 추가: REVIEW.BOOK_TSID -> BOOK.TSID
ALTER TABLE `REVIEW`
ADD CONSTRAINT `FK_REVIEW_BOOK`
FOREIGN KEY (`BOOK_TSID`) REFERENCES `BOOK` (`TSID`);